### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by voodoomg** [bolt/standard-project#6]
Deprecations will be fixed? =)
`User Deprecated: The "Psr\SimpleCache\CacheInterface" / "cache.app.simple" service is deprecated since Symfony 4.3. Use "Symfony\Contracts\Cache\CacheInterface" / "cache.app" instead.`
`The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "stof_doctrine_extensions" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.`
and 61 other

**Comment by bobdenotter** [comment]
Yes, we should try to fix most dependencies before a stable release :-)
